### ISSUE TITLE
TODO on deck/cards

### ISSUE THREAD

**Issue by phill2mj** [ninebolt/gloom-assistant#3]
- [x] final card schema design

- [x] deck sections (played/remainder)

- [x] card areas

- [x] card styling

- [x] card imagery

- [x] addCardAPI

- [x] Bless/Curse Cards
